language: java
sudo: false
install: mvn install -DskipFindBugs=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean verify -Dmaven.javadoc.skip=true
cache:
  directories:
  - $HOME/.m2