language: java
sudo: false
install: mvn install -DskipFindBugs=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean verify -DexcludeLiveServerTests=true -Dmaven.javadoc.skip=true
cache:
  directories:
  - $HOME/.m2
# whitelist
branches:
  only:
    - master
    - stable

# Codacy's test report runner for Jacoco
before_install:
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
# Codacy upload report
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml
# CodeClimate upload report
- ./cc-test-reporter format-coverage target/site/jacoco/jacoco.xml --input-type jacoco
- ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID