language: java
sudo: false

# CodeClimate:
#before_script:
#  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#  - chmod +x ./cc-test-reporter
#  - ./cc-test-reporter before-build
install: true
script: mvn clean verify -DexcludeLiveServerTests=true -Dmaven.javadoc.skip=true

cache:
  directories:
  - $HOME/.m2
branches:
  only:
    - develop
    - master

# Codacy's test report runner for Jacoco
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  # Codacy upload report
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r modules/jacoco-aggregator-module/target/site/jacoco-aggregate/jacoco.xml
  ## CodeClimate upload report
  #- ./cc-test-reporter format-coverage modules/jacoco-aggregator-module/target/site/jacoco-aggregate/jacoco.xml --input-type jacoco
  #- ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID