version: 2.1

orbs:
  github-maven-deploy: github-maven-deploy/github-maven-deploy@1.2.0

mvn-build-test-command: &mvn-build-test-command
  mvn-build-test-command: mvn verify -DexcludeLiveServerTests=true -Dmaven.javadoc.skip=true

mvn-collect-artifacts-command: &mvn-collect-artifacts-command
  mvn-collect-artifacts-command: |
    mkdir -p artifacts/cli
    cp modules/cli-module/target/*standalone* artifacts/cli/

mvn-deploy-command: &mvn-deploy-command
  mvn-deploy-command:  |
    mvn -s .circleci/maven-release-settings.xml clean deploy -DdeployAtEnd=true -DperformRelease=true -DskipTests -Dspotbugs.skip=true -Denforcer.skip=true -Djacoco.skip=true
    mvn license:remove
  context: RELEASE_PROFILE_BBOTTEMA

workflows:
  workflow:
    jobs:
      - github-maven-deploy/build-and-test:
          <<: *mvn-build-test-command
          <<: *mvn-collect-artifacts-command
          filters:
            branches:
              only: master

      - github-maven-deploy/approve-deploy-patch-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test
      - github-maven-deploy/approve-deploy-minor-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test
      - github-maven-deploy/approve-deploy-major-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test
      - github-maven-deploy/approve-deploy-as-is-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test

      - github-maven-deploy/deploy-patch-version:
          requires:
            - github-maven-deploy/approve-deploy-patch-version
          <<: *mvn-deploy-command
      - github-maven-deploy/deploy-minor-version:
          requires:
            - github-maven-deploy/approve-deploy-minor-version
          <<: *mvn-deploy-command
      - github-maven-deploy/deploy-major-version:
          requires:
            - github-maven-deploy/approve-deploy-major-version
          <<: *mvn-deploy-command
      - github-maven-deploy/deploy-as-is-version:
          requires:
            - github-maven-deploy/approve-deploy-as-is-version
          <<: *mvn-deploy-command
